name: Docker Image CI

on:
  push:
    branch: 'main'
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push on tag
        uses: docker/build-push-action@v4
        if: github.ref_name == 'v*'
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/binwalk:${{ github.ref_name }}
      -
        name: Build and push main
        uses: docker/build-push-action@v4
        if: github.ref_name == 'main'
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/binwalk:latest




